# fly.toml app configuration file generated for excalidraw-docgyq on 2025-06-03T05:54:55Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'excalidraw-docgyq'
primary_region = 'bom'

[build]

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
size = "shared-cpu-2x"
memory = "2gb"
cpus = 2
cpu_kind = "shared"
processes = ["app"]
